CREATE TABLE IF NOT EXISTS `chapitre` (
    id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    matiere_id INTEGER UNSIGNED NOT NULL,
    name VARCHAR(64),
    FOREIGN KEY (matiere_id) REFERENCES matieres(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);