CREATE TABLE IF NOT EXISTS `commentaires` (
    id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    author_id INTEGER UNSIGNED NOT NULL,
    sujet_id INTEGER UNSIGNED NOT NULL,
    content TEXT NOt NULL,
    created_time DATETIME NOT NULL DEFAULT NOW(),
    FOREIGN KEY (author_id) REFERENCES users(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (sujet_id) REFERENCES sujets(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);