CREATE TABLE IF NOT EXISTS `users` (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(32) NOT NULL,
    password VARCHAR(128) NOT NULL,
    permissions TINYINT UNSIGNED
)
